  export const EVENT_TYPES = {
  JOIN_QUEUE_R: 'JOIN_QUEUE',
  LEAVE_QUEUE_R: 'LEAVE_QUEUE',
  MATCH_MAKING_STATE_R: 'MATCH_MAKING_STATE',
  INIT_GAME: 'INIT_GAME',
  INCOMING_CATCH: 'INCOMING_CATCH',
} as const;



export type EVENT_TYPES = typeof EVENT_TYPES[keyof typeof EVENT_TYPES];

export type JOIN_QUEUE_R = typeof EVENT_TYPES.JOIN_QUEUE_R
export type LEAVE_QUEUE_R = typeof EVENT_TYPES.LEAVE_QUEUE_R
export type MATCH_MAKING_STATE = typeof EVENT_TYPES.MATCH_MAKING_STATE_R
export type INIT_GAME = typeof EVENT_TYPES.INIT_GAME
export type INCOMING_CATCH = typeof EVENT_TYPES.INCOMING_CATCH